### PR TITLE
Update dependencies, except librespot

### PR DESCRIPTION
**Pull request by Icelk**
There were no major changes to the code. Tested to function as expected.

### CODE REVIEW

**Comment by Icelk** [comment]
Blocked on rust 1.64
See https://github.com/Spotifyd/spotifyd/pull/1182#issuecomment-1460495599

**Comment by j-code-1** [comment]
stop

**Comment by eladyn** [comment]
Thanks. This PR “conflicts” a bit with #1174, which also improves the keyring thing. Not sure how to handle this best. I guess you either could leave the `keyring` update to the other PR, or we merge one of them first and see what git thinks. Either is fine to me. :)

**Comment by Icelk** [comment]
Sorry, I missed that. This doesn't update keyring. Let's merge #1174 first :)

This also blocks on #1182, since the MSRV is bumped there.

**Comment by Icelk** [comment]
I also realized we can remove `tokio-compat` now, which I've also done in this PR.

**Comment by slondr** [comment]
The check failure is just the 1.64 requirement; that should be resolved when the other PR is merged.

**Comment by slondr** [comment]
Ok, I think I fixed the merge conflicts

**Review by slondr — APPROVED** [review]

**Review by eladyn — APPROVED** [review]
Thanks!

**Comment by Icelk** [comment]
Great, thanks!

**Pull request merged**
