### PR TITLE
chore: add changelog

### PR DESCRIPTION
**Pull request by robinvd**
as discussed in https://github.com/Spotifyd/spotifyd/issues/702#issuecomment-719088894

ping @SirWindfield

### CODE REVIEW

**Review by JojiiOfficial — APPROVED** [review]

**Comment by SirWindfield** [comment]
Yep, something like this looks good!

**Review by SirWindfield — APPROVED** [review]

**Comment by SirWindfield** [comment]
Not sure why CI gets triggered though, I set the paths to only account for Rust related files:
https://github.com/Spotifyd/spotifyd/blob/133a1199f80c7c22f29a45226db3bb856b106a5b/.github/workflows/ci.yml#L3-L8

**Comment by SirWindfield** [comment]
Ah, looks like it is a conflict with the protected branch rule and the fact that the filter is applied inside the workflow:
https://github.community/t/path-filtering-on-required-pull-request-checks/18402/3

Just ping me if you want to get this merged into master, as I can still merge due to admin rights.

**Comment by robinvd** [comment]
@SirWindfield i think with you two approving, this can be merged.

**Pull request merged**
