### PR TITLE
Add Rodio Backend

### PR DESCRIPTION
**Pull request by Yarn**

### CODE REVIEW

**Comment by Yarn** [comment]
It looks like this actually requires bumping the librespot version. Getting compile errors in librespot with the version in Cargo.lock in master.

**Comment by SirWindfield** [comment]
Note to myself: I should stop working before I actually drank a coffee... Now I had to hard-reset -.-

**Comment by Yarn** [comment]
That version of librespot seems to work fine on osx with rodio at least. I pushed a `cargo.lock` with rodio and it's dependencies. It looks like CI still isn't happy with it still.

**Comment by SirWindfield** [comment]
Thank you for your contribution! The lockfile updated way too much dependencies and I lost track of what was actually happening so I merged the librespot update first and rebased. Kind of messed something up during that 🤔

**Pull request merged**
