### PR TITLE
Rename LICENCE -> LICENSE

### PR DESCRIPTION
**Pull request by schnitzeltony**
Sorry for nitpicking...

### CODE REVIEW

**Review by JojiiOfficial — APPROVED** [review]

**Review by robinvd — APPROVED** [review]

**Comment by schnitzeltony** [comment]
Ping on this great piece of change :grin:

**Comment by robinvd** [comment]
Ah there is an issue with CI staying 'waiting' on PRs with no code changes. @SirWindfield is i think the only one who can force merge

**Comment by SirWindfield** [comment]
Yep, only admins can force merge. I have no clue why it gets stuck on CI though...

**Comment by SirWindfield** [comment]
I'll try to investigate tomorrow evening and see why CI isn't working properly...

**Comment by SirWindfield** [comment]
Ahhhhhh! Why is it triggering now the every step? I checked it locally with `act` and it worked perfectly...

**Comment by SirWindfield** [comment]
Please work D:

**Comment by SirWindfield** [comment]
I've contacted the author of the package to get some help, maybe I am just using it wrong! I'll update you guys once I know more. If you want to get notified, you can subscribe to the update issue I've created for scenarios like these: https://github.com/Spotifyd/spotifyd/issues/604

**Comment by robinvd** [comment]
Great that you’re looking into it! @SirWindfield

**Pull request merged**
