### PR TITLE
Use --backend as fallback for backend in configuration file

### LINKED ISSUE #170: Using specifying backend through command line does not work
Whenever I run spotifyd using `--backend pulseaudio` (and without specifying it in a configuration file) it outputs the following:

```
No backend specified, defaulting to: alsa.
```

Whenever I specify the backend in a configuration file it works without problems. Example of configuration file:

```
[global]
backend=pulseaudio
```

### PR DESCRIPTION
**Pull request by bobvanderlinden**
Fixes #170 

As #170 describes, the `--backend` argument does not seem to do anything at the moment. When there is no configuration file available, the backend cannot be specified and it is falling back to its default (`alsa`).

This PR will make use of the `--backend` command line argument whenever the config option (in the configuration file) is not supplied.

Ideally I would say that the command line argument should always take preference over the configuration file, but currently username and password also seem to prioritize the configuration file above their command-line argument. That's outside the scope of this PR.

### CODE REVIEW

**Comment by SirWindfield** [comment]
Could you rebase your PR with the newest master from upstream? I just checked and your PR is branched off of `dbus_mpris`

**Comment by SirWindfield** [comment]
I updated the [README](https://github.com/SirWindfield/spotifyd/blob/master/README.md#contributing) file with instructions on how to use the newly tools. If you don't want to bother with it, just close this issue and I'll open a new one with your changes.

**Comment by bobvanderlinden** [comment]
@SirWindfield Strange, I'm not sure why it was based on such an old version of spotifyd. I noticed there were other issues with the command line options in general. It seemed the issue was mostly that whenever no configuration file was supplied, the parsing of the configuration is skipped (due to `return config;`). This also skips fetching the command line arguments.

I've updated the PR to resolve this issue.

I ran `rustfmt` on the changed file, but it showed unrelated warnings. I was not able to install `clippy`.

**Comment by SimonPersson** [comment]
Sorry, I forgot about this PR. I ran `rustfmt` for you, and merged. Thanks!

**Pull request merged**
