### PR TITLE
Guide for cross compiling using docker

### PR DESCRIPTION
**Pull request by mietzen**
Added a guide for cross compiling using docker for e.g. building arm64 as described in #1053

### CODE REVIEW

**Review by eladyn — CHANGES_REQUESTED** [review]
That looks great, thanks!

Since this is a new file in the docs folder, a link in `SUMMARY.md` would have to be added.

You can also check, if everything looks good by  building the docs with `mdbook`.

**Comment by mietzen** [comment]
I added the file to `SUMMARY.md` and tested it with `mdbook`, everything looked good 👍

**Review by eladyn — APPROVED** [review]
Amazing! Thank you.

**Comment by mietzen** [comment]
@eladyn I had a look at your CD Pipeline. It could be simplified using this approach. Would you be open / interested to accept a PR for your CI/CD Pipelines?

**Comment by eladyn** [comment]
Yes, absolutely! I was thinking that too, but currently our pipeline is really terrible, so I didn't want to put that burden on you. 😅 But if you're motivated that would be great!

**Pull request merged**
