### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by JojiiOfficial**
Tried to update as much dependencies as possible without breaking. Some adjustments in the src files were made. Mpris works for me. Some versions can't be updated unless we change some bigger parts of the code.

Closes #688, #627, #624, #305, #596

### CODE REVIEW

**Comment by slondr** [comment]
What's up with the stuff about `matches!` reported by https://github.com/Spotifyd/spotifyd/pull/695/checks?check_run_id=1294697342?

**Comment by JojiiOfficial** [comment]
Oh yeah lint 'errors'. I can fix them.

**Review by robinvd — APPROVED** [review]

**Comment by robinvd** [comment]
@JojiiOfficial the lint errors should be fixed in a seperate PR, if you could update the conflicts? i think just removing the 'fix lint errors' commit should fix it

**Comment by JojiiOfficial** [comment]
Removing the commit wasn't enough since #746 replaced the 'match block' with a 'matches macro' so I fixed the conflicts manually.

**Review by robinvd — APPROVED** [review]

**Comment by slondr** [comment]
Seems like this PR missed the removal of `failure' from Cargo.toml, which was merged yesterday

**Pull request closed without merging**
