### PR TITLE
Unify crate error

### PR DESCRIPTION
**Pull request by deantvv**
For #284

Also fix `clippy` warning and format

### CODE REVIEW

**Comment by deantvv** [comment]
@mainrs Could you please take a look at this and/or approve running workflow?

**Comment by JojiiOfficial** [comment]
Thanks for your contribution. Looks good to me. 
Please add reviewers to a new PR next time

**Review by JojiiOfficial — APPROVED** [review]

**Comment by deantvv** [comment]
@JojiiOfficial Thanks for reviewing the code and the tips.

CI lint failure seems not related to this PR.

**Review by robinvd — APPROVED** [review]

**Comment by deantvv** [comment]
@JojiiOfficial Could you check on this PR? Is there anything blocking this from being merged?

**Pull request closed without merging**
