### PR TITLE
Update librespot dependency

### LINKED ISSUE #85: Gapless support
There seems to be a small gap between tracks (~0.3 seconds)

Are there any plans to remove this in the future and support gapless playback?

### PR DESCRIPTION
**Pull request by marcelbuesing**
Waiting for https://github.com/librespot-org/librespot/pull/485 to be merged and a new librespot version.

Furthermore I'm unsure about the naming of strings in the `PLAYER_EVENT`, are those coming from somewhere specifically, e.g. `change`, `start`, `stop` ? 

For the gapless part alternatively using `.. Default::default()`, would have the same result, but might might make future changes non breaking (good or bad).

__Edit by SirWindfield:__
Fixes #85.

### CODE REVIEW

**Comment by SirWindfield** [comment]
I hope I do not break stuff and re-basing is the right approach here...

**Comment by SirWindfield** [comment]
I am currently debating on whether I should merge it or not. Merging this means that there won't be a new release on crates.io for sure until `librespot` releases their new patches. But it might mean that we can squash some bugs down.

Opinions?

**Comment by marcelbuesing** [comment]
I think I would wait until this is merged in librespot.

**Comment by ashthespy** [comment]
Just a heads up [librespot/0.1.2](https://crates.io/crates/librespot/0.1.2) is out, but we are planning to merge in https://github.com/librespot-org/librespot/pull/447 and push a bump release soon - which will probably require more churn for you, sorry!

**Comment by sashahilton00** [comment]
v0.1.3 is out. The volume control refactor PR was included in v0.1.3, so watch out for a small breaking change in that `--linear-volume` has changed to `--volume-ctrl` with a few options. @ashthespy if you could document those and the cubic mixer PR in the wiki at some point, that'd be great.

**Comment by marcelbuesing** [comment]
I think this could be merged now. Please review again.

**Comment by loki7990** [comment]
Just a heads-up, line 83 of setup.rs in the `bump-librespot` branch has a misspelled `VolumeCtrl`. Currently it's `VolumeCtl`.

**Comment by marcelbuesing** [comment]
> Just a heads-up, line 83 of setup.rs in the `bump-librespot` branch has a misspelled `VolumeCtrl`. Currently it's `VolumeCtl`.

Finally fixed =)

**Comment by codicodi** [comment]
I've been using this PR for a while and it seems to somehow break MPRIS play-pause functionality. `playerctl play-pause` only can start playback but cannot pause it anymore.

**Comment by marcelbuesing** [comment]
I just rebased this PR on top of the latest changes in spotifyd, I'm confident that librespot might soon support tokio 1.0 so it would probably be good to update to librespot 0.1.3 before the next major breaking change.

**Comment by robinvd** [comment]
Amazing to hear they might update to 1.0!, ill look at this pr soon

**Review by robinvd — APPROVED** [review]

**Review by SimonPersson — DISMISSED** [review]

**Review by robinvd — APPROVED** [review]

**Review by SimonPersson — APPROVED** [review]

**Pull request merged**
