### PR TITLE
refactor mpris implementation as specified in issue #322

### LINKED ISSUE #161: Can't get dbus support working
Built with pulseaudio and dbus_mpris features. The client itself works beautifully, but I can't connect to the bus. Anyone have any ideas?  

image

### LINKED ISSUE #258: Crash on playerctl command
When running a command from `playerctl` (over dbus), spotifyd crashes with 

```
[ERROR] 11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
Caught panic with message: called `Result::unwrap()` on an `Err` value: Error(Executor(EnterError { reason: "attempted to run an executor while another executor is already running" }), "https://api.spotify.com/v1/me/player")
```

This is git master at the time of writing with all features enabled.

More debug log for context:
```
...
11:47:05 [DEBUG] tokio_core::reactor: loop poll - 1.597µs
11:47:05 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2643, tv_nsec: 516027470 }
11:47:05 [DEBUG] tokio_core::reactor: loop process, 8.665µs
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [DEBUG] dbus_tokio::adriver: D-Bus i/o poll ready: 29 is Ready(Readable)
11:47:07 [DEBUG] dbus_tokio::adriver: D-Bus i/o unix ready: 29 is Readable | Aio
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [DEBUG] dbus_tokio::adriver: handle_msgs: (MethodCall, Some("/org/mpris/MediaPlayer2"), Some("org.freedesktop.DBus.Properties"), Some("GetAll"))
11:47:07 [DEBUG] tokio_core::reactor: loop poll - 1.603341812s
11:47:07 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2645, tv_nsec: 119382030 }
11:47:07 [DEBUG] tokio_core::reactor: loop process, 9.295µs
11:47:07 [DEBUG] dbus_tokio::adriver: Polling message stream
11:47:07 [DEBUG] dbus_tokio::adriver: msgstream found Ok(Ready(Some((MethodCall, Some("/org/mpris/MediaPlayer2"), Some("org.freedesktop.DBus.Properties"), Some("GetAll")))))
11:47:07 [TRACE] mio::poll: [<unknown>:787] registering with poller
11:47:07 11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(4194303)
[ERROR] 11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
Caught panic with message: called `Result::unwrap()` on an `Err` value: Error(Executor(EnterError { reason: "attempted to run an executor while another executor is already running" }), "https://api.spotify.com/v1/me/player")
11:47:07 [TRACE] reqwest::client: [<unknown>:578] response receiver is canceled
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 0 events, 0.000s
11:47:07 [DEBUG] librespot_connect::spirc: drop Spirc[0]
11:47:07 [DEBUG] librespot_playback::player: Shutting down player thread ...
11:47:07 [DEBUG] librespot_playback::player: drop Player[0]
11:47:07 [DEBUG] librespot_core::session: drop Session[0]
11:47:07 [DEBUG] librespot::component: drop AudioKeyManager
11:47:07 [DEBUG] librespot::component: drop ChannelManager
11:47:07 [DEBUG] librespot::component: drop MercuryManager
11:47:07 [DEBUG] dbus_tokio::adriver: Dropping AMessageStream
11:47:07 [DEBUG] dbus_tokio::adriver: AMessageStream telling ADriver to quit
11:47:07 [TRACE] tokio_threadpool::pool: [<unknown>:138] shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
11:47:07 [TRACE] tokio_threadpool::pool: [<unknown>:186]   -> transitioned to shutdown
11:47:07 [TRACE] tokio_threadpool::pool: [<unknown>:207]   -> shutting down workers
11:47:07 [TRACE] mio::poll: [<unknown>:907] deregistering handle with poller
11:47:07 [DEBUG] tokio_reactor: dropping I/O source: 0
11:47:07 [DEBUG] tokio_reactor: dropping I/O source: 3
11:47:07 [TRACE] mio::poll: [<unknown>:907] deregistering handle with poller
11:47:07 [DEBUG] tokio_reactor: dropping I/O source: 1
11:47:07 [TRACE] mio::poll: [<unknown>:907] deregistering handle with poller
11:47:07 [DEBUG] tokio_reactor: dropping I/O source: 2
11:47:07 [DEBUG] librespot_core::session: drop Dispatch
11:47:07 [TRACE] mio::poll: [<unknown>:907] deregistering handle with poller
11:47:07 [DEBUG] tokio_reactor: dropping I/O source: 5
11:47:07 [DEBUG] tokio_reactor: dropping I/O source: 4
```

### PR DESCRIPTION
**Pull request by reschandreas**
Closes #161.
Fixes #258, although a `rspotify` merge is preferred.

__Note from SirWindfield:__ I had to edit your original comment as Github only checks for closing keywords on the first comment 😄

### CODE REVIEW

**Comment by SirWindfield** [comment]
Thanks for the contribution. I also started refactoring the code. But I will just use your code as the base and integrate my changes as well :)

**Comment by SirWindfield** [comment]
Closes #161.
Fixes #258, although a `rspotify` merge is preferred.

**Comment by SirWindfield** [comment]
Might close #153, feedback needed.

**Comment by taigrr** [comment]
@SirWindfield would we be able to package and release this now? it fixes (at least for me) 4 separate issues ( #328 #271 #258 #153)

**Comment by SirWindfield** [comment]
v0.2.18 is released @taigrr

**Comment by SirWindfield** [comment]
@taigrr So I just released a new version v0.2.19 with an MPRIS fix. The archives should all work now again :)

**Pull request merged**
