### PR TITLE
Expose librespots support for limiting the cache size 

### LINKED ISSUE #1066: limit cache size config
Thanks for spotifyd. I have to clear my cache manually every two weeks, because the cache on my raspberry2 is full and the daemon — and of coarse other processes as well — stucks and doesn't play any songs.
Limit  the maximum cache size possibility in config file would be nice.
Delete the oldest when max size is reached would be the smartest way, if it is easy to implement. But clear cache completely is also a valid solution for me and the easiest way....
THX

### PR DESCRIPTION
**Pull request by weiznich**
Fixes #1066

### CODE REVIEW

**Review by eladyn — CHANGES_REQUESTED** [review]
Thanks for the PR!

There are still some places, where you'd need to add the new flag as well:

- [merging of the different configuration sources](https://github.com/Spotifyd/spotifyd/blob/7cd64ff1f39c457fa92e8d15649fab02ddff013d/src/config.rs#L509-L529), otherwise the value can't be set in the config file
- [struct debugging](https://github.com/Spotifyd/spotifyd/blob/7cd64ff1f39c457fa92e8d15649fab02ddff013d/src/config.rs#L442-L466), so that the value is logged with `--verbose`
- [docs](https://github.com/Spotifyd/spotifyd/blob/7cd64ff1f39c457fa92e8d15649fab02ddff013d/docs/src/config/File.md?plain=1#L9-L101), if possible, with some documenting lines

**Review by eladyn — APPROVED** [review]
LGTM and works as it should!

**Comment by weiznich** [comment]
@slondr Any chance on merging this?

**Review by robinvd — APPROVED** [review]

**Review by slondr — APPROVED** [review]
I haven't tested this out in a real setup but the code changes look fine

**Pull request merged**
