### PR TITLE
add windows support - see (#602)

### PR DESCRIPTION
**Pull request by frankmoskal**
See (#602) for details. All credit goes to  @JCapucho.

My changes are:
- rebasing against master
- making rodio the default background (platform-independent) & update windows-specific dependencies
- making the default config location based on [directories](https://docs.rs/directories/1.0.1/directories/struct.BaseDirs.html) without a fallback  + a bit of logging

Feel free to change whatever! I've really only tested compiling this with msvc, but it works for me.

### CODE REVIEW

**Comment by frankmoskal** [comment]
I wanted to clean this up a little - will reopen at a later date.

**Comment by Alexhuszagh** [comment]
@frankmoskal This doesn't seem to work: a great example is daemonize doesn't support Windows. There's a lot of imports that simply aren't supported on Windows, like `use std::os::unix`, and I'm not sure how to clean that up without a substantial rewrite.

**Comment by Alexhuszagh** [comment]
Ok the dependencies that don't seem to work are as follows:

- syslog (a Unix-only system logger)
- dbus, dbus-tokio (optional, no big issue)
- alsa (optional, not used for our backend)
- daemonize

The main issue is daemonize, which seems to be unmaintained, Unix-specific, and may take some work to port over. syslog v5 supports Windows, while v4 and v4.0.1 only support Unix.

**Comment by Alexhuszagh** [comment]
The closest example I can see to daemonize is daemon-rs, which should be a trivial replacement (if it works on non-Linux Unix-Like systems and macOS), since the only code requiring daemon support is:

```rust
    if is_daemon {
        info!("Daemonizing running instance");

        let mut daemonize = Daemonize::new();
        if let Some(pid) = internal_config.pid.as_ref() {
            daemonize = daemonize.pid_file(pid);
        }
        match daemonize.start() {
            Ok(_) => info!("Detached from shell, now running in background."),
            Err(e) => error!("Something went wrong while daemonizing: {}", e),
        };
    }
```

**Comment by Alexhuszagh** [comment]
I'm unsure of how we'd port daemonize, since the original relies on fcntl for the Python source, which is Unix-specific, just like the port.

**Comment by frankmoskal** [comment]
@Alexhuszagh You'll actually want to look at [frankmoskal-windows-dev](https://github.com/frankmoskal/spotifyd/tree/frankmoskal-windows-dev ) - I moved things over to that branch after closing this MR to make things a bit easier on my end.

**Comment by Alexhuszagh** [comment]
@frankmoskal Ah my bad, I didn't see anything obvious in the branch list and just assumed it was on master.

**Pull request closed without merging**
