### PR TITLE
feat(config): add initial volume

### PR DESCRIPTION
**Pull request by sflip**
This adds a config option `initial_volume` to set the initial volume, so it's not set to 100% [which may cause little kittens or their owners to die](https://github.com/Spotifyd/spotifyd/issues/445#issuecomment-604911070).

The setting is of course optional to be backwards compatible, so if it's not set, volume initialization isn't changed. Also, if the value could not be parsed, it prints a warning to help users and gently ignores it.

(This is my first contribution, please be gentle with me :slightly_smiling_face:)

### CODE REVIEW

**Comment by mirko** [comment]
Can't tell you how glad I am about this feature. Working like a charme, finally switching from librespot. Thanks!

**Comment by mzanetti** [comment]
Just managed to update my machine. Thank you so much!

I'm wondering a bit tho, wouldn't it make (more) sense to store the last used volume and restore that? That way a user wouldn't need to touch the config file at all. Seems to be what pretty much all other speakers/media players are doing.

**Comment by SirWindfield** [comment]
It should actually do that already. Last time I tinkered around with the library I set it to cache the audio levels. There should be a json file inside the cache directory that contains the value. Not sure what broke it though.

**Comment by sflip** [comment]
@mzanetti Agreed, restoring the last volume would be a lot better! This config feature can be considered a quickwin that seemed easier to implement in order to "fix" #445. 

@SirWindfield That's interesting! Really unfortunate that it broke. Maybe I'd like to look into that as well. But would that be the source of `librespot` rather than `spotifyd`, then?

**Comment by SirWindfield** [comment]
I think so, yes.

**Pull request merged**
