### PR TITLE
Add volume property

### PR DESCRIPTION
**Pull request by izissise**
https://github.com/Spotifyd/spotifyd/issues/397

Simple PR that expose the Volume through dbus 

Tested the volume is zero when nothing is playing and initial_volume when playing

It's basically  zack6849 patch

### CODE REVIEW

**Comment by robinvd** [comment]
Looks good! looks like the lint is failing though, but i do find this one to be a bit pedantic

**Review by robinvd — DISMISSED** [review]

**Comment by izissise** [comment]
I would fix it, but it's not part of the modified files

**Comment by robinvd** [comment]
Oh thats weird, maybe the lint is new. When its fixed we can restart ci

**Comment by robinvd** [comment]
The lint errors seem to be fixed in #695. So after that we should be able to merge this.

**Comment by izissise** [comment]
Nice!, I'll rebase once it's merged :)

**Review by JojiiOfficial — DISMISSED** [review]

**Review by slondr — APPROVED** [review]

**Review by robinvd — APPROVED** [review]

**Pull request merged**
